development:
    AWS_ACCESS_KEY: AKIAIXSKGADXM2VLXW7A
    AWS_SECRET_TOKEN: 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
    AWS_BUCKET: 'freeindianshopproduct'
    
production:
    AWS_ACCESS_KEY: AKIAIXSKGADXM2VLXW7A
    AWS_SECRET_TOKEN: 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
    AWS_BUCKET: 'freeindianshopproduct'
   
test:
    AWS_ACCESS_KEY: AKIAIXSKGADXM2VLXW7A
    AWS_SECRET_TOKEN: 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
    AWS_BUCKET: 'freeindianshopproduct'
  