development:
    AWS_ACCESS_KEY: AKIAI3XF7D56OTPTCYNA 
    AWS_SECRET_TOKEN: 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
    AWS_BUCKET: 'freeindianshop'
production:
    AWS_ACCESS_KEY: ENV['AWS_ACCESS_KEY']
    AWS_SECRET_TOKEN: ENV['AWS_SECRET_TOKEN']
    AWS_BUCKET: ENV['AWS_BUCKET']
test:
    AWS_ACCESS_KEY: AKIAI3XF7D56OTPTCYNA
    AWS_SECRET_TOKEN: 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
    AWS_BUCKET: 'freeindianshop'