development:
    AWS_ACCESS_KEY: AKIAIVY5R7JMIJ4MPRPQ
    AWS_SECRET_TOKEN: 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
    AWS_BUCKET: 'freeindianshopproduct'
    AWS_REGION : 'US East (Ohio)'
production:
    AWS_ACCESS_KEY: AKIAIVY5R7JMIJ4MPRPQ
    AWS_SECRET_TOKEN: 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
    AWS_BUCKET: 'freeindianshopproduct'
    AWS_REGION : 'US East (Ohio)'
test:
    AWS_ACCESS_KEY: AKIAIVY5R7JMIJ4MPRPQ
    AWS_SECRET_TOKEN: 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
    AWS_BUCKET: 'freeindianshopproduct'
    AWS_REGION : 'US East (Ohio)'